### ISSUE TITLE
error when importing product with sku containing double quotes

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-node-product-csv-sync#149] opened 2016-12-01 16:57 UTC
When trying to import following CSV file:
```
productType,sku,variantId 
ptype,"eqsmlg-9'2""",1
```
the import fails with following error:

> BadRequest: Malformed parameter: where: Syntax error while parsing 'where'. Invalid input '"', expected comma or ')' (line 1, column 35):
masterVariant(sku in ("eqsmlg-9'2"")) or variants(sku in ("eqsmlg-9'2""))
                                  ^
    at /app/node_modules/sphere-node-sdk/lib/services/base.js:501:22
    at ProductProjectionService.BaseService._wrapResponse (/app/node_modules/sphere-node-sdk/lib/services/base.js:516:11)
    at /app/node_modules/sphere-node-sdk/lib/services/base.js:358:40
    at Request._callback (/app/node_modules/sphere-node-sdk/lib/connect/rest.js:164:14)
    at Request.self.callback (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1202:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1150:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by Siilwyn** [comment] 2016-12-01 17:46
Maybe: https://github.com/sphereio/sphere-node-product-csv-sync/blob/af48a72ab8e4fec86ef429269eccb8403cf77231/src/coffee/import.coffee#L183

**Comment by hisabimbola** [comment] 2016-12-06 06:09
@stmeissner I think this is not a bug with the tool, the error reported is from the API. I tried this on impex too and got same error.

We should probably report it to them.

**Comment by hisabimbola** [comment] 2016-12-06 06:10
I will be closing this for now, please reopen if problem persists with the tool.

**Comment by Siilwyn** [comment] 2016-12-06 08:40
I don't think we should close issues that are not fixed or at least wait for the reporter to respond :) As far as I could see the error comes from our side.
The 'abandoned' status is for valid issues that we won't fix for a long time.

**Comment by hisabimbola** [comment] 2016-12-06 11:39
Scratch my first comment @stmeissner I looked into this more and discovered that it's an escape issue, not the API

and it's an issue for couple of other modules.

We will look deeper into this and see how to fix this

**Comment by ebonertz** [comment] 2016-12-06 21:47
Yes definitely an issue with escaping the " character. Thanks for looking into it. Please keep me updated on this issue

**Closed** 2017-03-10 13:34 UTC
Labels: Status: Review, Type: Bug
