### ISSUE TITLE
updating product name is ignored

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-node-product-csv-sync#144] opened 2016-11-22 10:19 UTC
when I try to update the product name with a new value I get the message
`'Product update not necessary.'`
although the value is different to the existing name.

the CSV file I've used contains the columns: 
sku, productType, name.en

**Comment by junajan** [comment] 2016-11-24 17:21
We found out that the name is being updated when the product is matched by its ID or SKU together with variantId.

If only the SKU is provided then variants get updated but the base product (name, slug .. etc) is left without any change which relates to this issue: https://github.com/sphereio/sphere-node-product-csv-sync/issues/107

I will close this issue because it is caused by errors described in the issue mentioned above.

**Closed by junajan** 2016-11-24 17:21 UTC
Labels: bug
